name: Unit Testing
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - 'hack/**'

jobs:
  test:
    name: Launch Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Launch Test (Docker Container)
        run: make unit
